import type { CoupledConfig } from "../coupledTypes";

export const config: CoupledConfig = {
  warmup_min: 120,
  drain_min: 240,
  shared_group_policy: "reject_unresolved",
  stress_events: [],
  fleets: [
    {
      kind: "bus",
      vehicles: 2,
      chargers: 1,
      battery_capacity_kwh: 300,
      initial_soc_pct: 50,
      reserve_soc_pct: 10,
      charge_target_soc_pct: 85,
      charger_kw: 80,
      mission_energy_kwh: 8,
      service_duration_min: 15,
      return_min: 10,
      departure_lead_min: 45,
      departure_buffer_min: 10,
      arrival_allowance_min: 30,
      coverage_pct: 100,
    },
  ],
  power: {
    grid_import_limit_kw: 3500,
    grid_export_limit_kw: 2000,
    background_load_kw: 22000,
    chp_output_kw: 18000,
    pv_capacity_kwp: 7000,
    pv_peak_factor: 0.55,
    apron_transformer_kva: 4500,
    parking_transformer_kva: 2500,
    power_factor: 0.95,
    transformer_efficiency: 0.98,
    charging_efficiency: 0.92,
    battery_capacity_kwh: 0,
    battery_power_kw: 1000,
    battery_initial_soc_pct: 50,
    battery_reserve_pct: 10,
    battery_efficiency: 0.95,
    parking_sessions: 200,
    parking_charger_kw: 11,
  },
};
