import type { FlightPlanSnapshot } from "../flightplanTypes";

export const plan: FlightPlanSnapshot = {
  snapshot_id: "a".repeat(64),
  content_sha256: "a".repeat(64),
  source_pdf_sha256: "b".repeat(64),
  service_date: "2026-10-03",
  source_data_date: "2026-10-02",
  timezone: "Europe/Berlin",
  source_url: "https://www.munich-airport.de/saisonflugplan",
  imported_at: "2026-10-03T08:00:00Z",
  parser_version: "muc_season_pdf_v1",
  evidence_level: "published_schedule_not_actual",
  import_method: "manual_user_upload",
  arrival_entry_count: 1,
  departure_entry_count: 1,
  duplicate_rows_removed: 0,
  possible_shared_flight_groups: 0,
  parsed_schedule_rows: 2,
  hourly_counts: Array.from({ length: 24 }, (_, hour) => ({
    hour,
    arrivals: hour === 6 ? 1 : 0,
    departures: hour === 9 ? 1 : 0,
  })),
  warnings: ["Kein Live-Status"],
  rows: [
    {
      entry_id: "a".repeat(16),
      direction: "arrival",
      flight_number: "XY101",
      airline: "Test Air",
      counterpart_iata: "AAA",
      terminal: "2",
      scheduled_local: "2026-10-03T06:25:00+02:00",
      scheduled_utc: "2026-10-03T04:25:00+00:00",
      source_pages: [1],
      possible_shared_group: null,
    },
    {
      entry_id: "b".repeat(16),
      direction: "departure",
      flight_number: "XY102",
      airline: "Test Air",
      counterpart_iata: "BBB",
      terminal: "1",
      scheduled_local: "2026-10-03T09:00:00+02:00",
      scheduled_utc: "2026-10-03T07:00:00+00:00",
      source_pages: [1],
      possible_shared_group: null,
    },
  ],
};
